- name: start the libvirtd service
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true
  become: true

- name: Reboot
  ansible.builtin.reboot:
  when: not ansible_connection == 'local'