- name: Install core
  ansible.builtin.dnf:
    name: "@virtualization"
    state: present
  become: true
  when: not optional_packages
  notify: start the libvirtd service


# Fix: https://github.com/ansible/ansible/issues/67187
- name: Install all
  ansible.builtin.shell: dnf group install --with-optional virtualization
  args:
    creates: somelog.txt
  become: true
  when: optional_packages
  notify: start the libvirtd service
