- name: install KVM & Virt-Manager
  hosts: localhost #, node
  vars:
    optional_packages: true

  roles:
  - dev/ansible-role-KVM
  - dev/ansible-role-Virt-Manager
  - dev/ansible-role-Libvirt-Network-start-On-Boot
#  - UniInc.KVM
#  - UniInc.Virt-Manager
